################################################################################
#
#  This file is part of SplashSync Project.
# 
#  Copyright (C) Splash Sync <www.splashsync.com>
# 
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# 
#  For the full copyright and license information, please view the LICENSE
#  file that was distributed with this source code.
# 
#  @author Bernard Paquier <contact@splashsync.com>
#
################################################################################

################################################################################
# Docker Compose File
#
# This Docker File intend to Create a Complete Dev Environnement
# for Splash Optilog Connector
#
# For a faster access to you container, you can add this IP to /etc/hosts
# 
# 172.106.0.100         toolkit.optilog.local
#
################################################################################


version: '2'

services:
    
    ################################################################################
    # Splash Toolkit Container   
    toolkit:
        image: 'splashsync/toolkit'
        container_name: optilog-toolkit
        volumes:
            # Specify Local Configuration File
            - './docker/toolkit/splash.yml:/app/config/packages/splash.yml:ro'
            # Uncomment to use Local Sources instead of Release
            - './:/app/vendor/splash/optilog/:ro'
        hostname:           toolkit.optilog.local
        networks:
            optilog:        { ipv4_address: 172.106.0.100, aliases: [ toolkit.optilog.local ] }
            splashsync:     { aliases: [ toolkit.optilog.local ] }

    ################################################################################
    # PHP 8.1
    php-8.1:
        image:          registry.gitlab.com/badpixxel-projects/php-sdk:php-8.1
        container_name: optilog-bundle-8.1
        volumes:
            - ./:/var/www/html
            - vendor-php81:/var/www/html/vendor

    ################################################################################
    # PHP 8.0
    php-8.0:
        image:          registry.gitlab.com/badpixxel-projects/php-sdk:php-8.0
        container_name: optilog-bundle-8.0
        volumes:
            - ./:/var/www/html
            - vendor-php80:/var/www/html/vendor

networks:
    ################################################################################
    # Default Private Network    
    optilog:
        driver: bridge
        ipam:
            config:
                - subnet: 172.106.0.0/24
    ################################################################################
    # External Splash Network
    splashsync:
        external: true

volumes:
    vendor-php81: ~
    vendor-php80: ~