services:
    ################################################################################
    # SPLASH Optilog Connector Service
    splash.connectors.optilog:
        class: Splash\Connectors\Optilog\Services\OptilogConnector
        arguments:  [ "@event_dispatcher", "@logger" ]
        tags:       
            - { name: "splash.connector"}

#    ################################################################################
#    # Enables Dependency Injection in Controller Actions
#    Splash\Connectors\Optilog\Controller\:
#        resource: '../../Controller'
#        public: true
#        tags: ['controller.service_arguments']