services:
    
    ################################################################################
    # SPLASH Optilog Connector Service
    splash.connectors.optilog:
        class: Splash\Connectors\Optilog\Services\OptilogConnector
        arguments:  [ "@event_dispatcher", "@logger" ]
        tags:       
            - { name: "splash.connector"}