
splash:

################################################################################    
# Configure Splash Bundle Parameters Cache    
# Cache is Enabled by Default to Store Custom Connectors Configuration
# If disabled, configuration must be store in Static, on connections section
################################################################################    
#    cache: 
#        enabled: false    
#        lifetime: 10

    # Allow Notifications for Generic Users   
    notify: ["ROLE_USER"]
    
################################################################################    
# List of Availables Connector Connections
################################################################################    

    connections:
        
        ########################################################################
        # Optilog Default
#        optilog:
#            id:                 ThisIsOptilogWsId
#            key:                ThisIsNotASecretKeyForOptilog
#            name:               Optilog API V1
#            connector:          optilog
#            ########################################################################
#            # FAKE CREDENTIALS : ASK YOURS TO YOUR MAIN OPTILOG CONTACT
#            ########################################################################
#            config:
#                WsHost:         https://api.preprod.geolie.net/wsgestinbox_V2.asmx
#                ApiUser:        splash
#                ApiPwd:         ThisIsSecretApiPwd
#                ApiKey:         ThisIsSecretApiKey
#                ApiOp:          ThisIsSecretApiOp
#                dfStock:        Divers
#                dfGamme:        Nouveaux

        ########################################################################
        # Optilog API V2
        optilog-v2:
            id:                 ThisIsOptilogWsId
            key:                ThisIsNotASecretKeyForOptilog
            name:               Optilog API V2
            connector:          optilog
            ########################################################################
            # FAKE CREDENTIALS : ASK YOURS TO YOUR MAIN OPTILOG CONTACT
            ########################################################################
            config:
                WsHost:         https://api.preprod.geolie.net/wsgestinbox_V2.asmx
                ApiUser:        splash.test
                ApiPwd:         54fbf20683a4b68a079dcfb348a121eb
                ApiKey:         08e789053de980e0f1ac70a61125a17d
                ApiOp:          TEST00016
                dfStock:        Principal
                dfGamme:

        ########################################################################
        # Optilog API ReCommerce
        optilog-re:
            id:                 ThisIsOptilogReWsId
            key:                ThisIsNotASecretKeyForOptilogRe
            name:               Optilog ReCommerce
            connector:          optilog
            ########################################################################
            # FAKE CREDENTIALS : ASK YOURS TO YOUR MAIN OPTILOG CONTACT
            ########################################################################
            config:
                WsHost:         https://api.preprod.geolie.net/wsgestinbox_V2.asmx
                ApiUser:        splash_test_REC
                ApiPwd:         a92a8bb72089478f692e165337cd07ab
                ApiKey:         d6d269952320c4fb5e50f278c94a098c
                ApiOp:          B2C
                dfStock:        Mobile
                dfGamme: